// cracked by vikee 2/09/2002   vikee@263.net
// by snowcat jan 22 1998

#include <ansi.h>
#include <quest.c>

// the quest format is the following mapping:
// daoxing :     type     name     id            object         amount
//--------------------------------------------------------------------
//  1000   : ({ "find",  "秘笈",   "mi ji" ,     "",             "1" }), 
//  5000   : ({ "give",  "灾民",   "zai min" ,   "白银(silver)", "5" }), 
// 12000   : ({ "kill",  "白骨精", "baigu jing", "",             "3" });
 
//找一本秘笈，救济灾民五两银子，三打白骨精．．．．．．

mapping quests_misc = ([
      50 : ({ "find", YEL"绣花小鞋"NOR,  "shoes",              "", "1" }),
     100 : ({ "find", "牛皮靴",          "leather boots",      "", "1" }),
     150 : ({ "find", "花褶靴",          "flower boots",       "", "1" }),
     200 : ({ "find", "乌绫巾",          "wuling jin",         "", "1" }),
     250 : ({ "find", "毡帽",            "hat",                "", "1" }),
     300 : ({ "find", "圆口布鞋",        "shoes",              "", "1" }),
     350 : ({ "find", RED"软香鞋"NOR,    "shoes",              "", "1" }),
     400 : ({ "find", "“金”项链",      "xiang lian",         "", "1" }),
     450 : ({ "find", HIB"蓝色冰块"NOR,  "lan bingkuai",       "", "1" }),
     500 : ({ "find", "花籽",            "seed",               "", "1" }),

    1000 : ({ "find", "金戒指",          "jin jiezhi",         "", "1" }),
    1100 : ({ "find", "金项链",          "xiang lian",         "", "1" }),
    1200 : ({ "find", "白金项圈",        "baijin xiangquan",   "", "1" }),
    1300 : ({ "find", "紫金戒指",        "zijin jiezhi",       "", "1" }),
    1400 : ({ "find", "鎏金腕链",        "liujin wanlian",     "", "1" }),

    1510 : ({ "find", "琥色毫毛",        "amber hair",         "", "1" }),
    1515 : ({ "find", "黑色毫毛",        "black hair",         "", "1" }),
    1520 : ({ "find", "蓝色毫毛",        "blue hair",          "", "1" }),
    1525 : ({ "find", "棕色毫毛",        "brown hair",         "", "1" }),
    1530 : ({ "find", "绿色毫毛",        "green hair",         "", "1" }),
    1535 : ({ "find", "靛色毫毛",        "indigo hair",        "", "1" }),
    1540 : ({ "find", "绛色毫毛",        "magenta hair",       "", "1" }),
    1545 : ({ "find", "栗色毫毛",        "maroon hair",        "", "1" }),
    1550 : ({ "find", "橙色毫毛",        "orange hair",        "", "1" }),
    1555 : ({ "find", "粉色毫毛",        "pink hair",          "", "1" }),
    1560 : ({ "find", "赤色毫毛",        "red hair",           "", "1" }),
    1565 : ({ "find", "绯色毫毛",        "scarlet hair",       "", "1" }),
    1570 : ({ "find", "紫色毫毛",        "violet hair",        "", "1" }),
    1575 : ({ "find", "白色毫毛",        "white hair",         "", "1" }),
    1580 : ({ "find", "黄色毫毛",        "yellow hair",        "", "1" }),

    2100 : ({ "find", HIB"桂花"NOR,      "gui hua",            "", "1" }),
    2200 : ({ "find", HIB"野菊花"NOR,    "ju hua",             "", "1" }),
    2300 : ({ "find", HIB"矢车菊"NOR,    "ju hua",             "", "1" }),
    2400 : ({ "find", HIB"白菊花"NOR,    "ju hua",             "", "1" }),
    2500 : ({ "find", HIB"蔷薇花"NOR,    "rose",               "", "1" }),
    3000 : ({ "find", "水晶腰牌",        "yao pai",            "", "1" }),

    3100 : ({ "find", "〖三字经〗",      "book",               "", "1" }),
    3200 : ({ "find", "〖风水〗",        "book",               "", "1" }),
    3300 : ({ "find", "〖女儿经〗",      "book",               "", "1" }),
    3400 : ({ "find", "〖拳经〗",        "quan jing",          "", "1" }),
    3500 : ({ "find", "〖刀法入门〗",    "blade book",         "", "1" }),
    3600 : ({ "find", "〖金刚经〗",      "jingang",            "", "1" }),
    3700 : ({ "find", "〖拳法入门〗",    "unarmed book",       "", "1" }),
    3800 : ({ "find", "〖青莲剑谱〗",    "jian pu",            "", "1" }),
    3900 : ({ "find", "〖道德经〗",      "daodejing",          "", "1" }),
    4000 : ({ "find", "〖千字文〗",      "qian",               "", "1" }),

    4100 : ({ "find", "硬木盔",          "ying mukui",         "", "1" }),
    4200 : ({ "find", "鹿皮鞋",          "pi xie",             "", "1" }),
    4300 : ({ "find", "水牛皮靴",        "shuiniu pixue",      "", "1" }),
    4400 : ({ "find", "登山屐",          "dengshan ji",        "", "1" }),
    4500 : ({ "find", "黑丝帽",          "si mao",             "", "1" }),

    5000 : ({ "find", HIB"蓝玫瑰"NOR,    "flower",             "", "1" }),
    5100 : ({ "find", HIB"黑郁金香"NOR,  "flower",             "", "1" }),
    5200 : ({ "find", HIB"薄雪花"NOR,    "flower",             "", "1" }),
    5300 : ({ "find", HIB"玉白露"NOR,    "flower",             "", "1" }),
    5400 : ({ "find", HIB"野风信子"NOR,  "flower",             "", "1" }),
    5500 : ({ "find", HIB"睡芙蓉"NOR,    "flower",             "", "1" }),
    5600 : ({ "find", HIB"紫蔷薇"NOR,    "flower",             "", "1" }),
    5700 : ({ "find", HIB"大丽花"NOR,    "flower",             "", "1" }),
    5800 : ({ "find", HIB"勿忘我"NOR,    "flower",             "", "1" }),
    5900 : ({ "find", HIB"白玫瑰"NOR,    "flower",             "", "1" }),
    6000 : ({ "find", HIB"翡翠绿"NOR,    "flower",             "", "1" }),
    6100 : ({ "find", HIB"雪腊梅"NOR,    "flower",             "", "1" }),
    6200 : ({ "find", HIB"曼陀罗"NOR,    "flower",             "", "1" }),
    6300 : ({ "find", HIB"睡莲"NOR,      "flower",             "", "1" }),


    6400 : ({ "find", "凤冠",            "jin fengguan",       "", "1" }),
    6500 : ({ "find", "龙冠",            "jin longguan",       "", "1" }),
    6600 : ({ "find", "云靴",            "yun xue",            "", "1" }),
    6700 : ({ "find", "牛皮帽",          "niu pimao",          "", "1" }),
    6800 : ({ "find", "银项链",          "silver necklace",    "", "1" }),
    6900 : ({ "find", "银戒指",          "silver ring",        "", "1" }),
    7000 : ({ "find", "银戒指",          "yin jie",            "", "1" }),
    7100 : ({ "find", "银手镯",          "silver wrist",       "", "1" }),
    7200 : ({ "find", "白金戒指",        "bai jie",            "", "1" }),
    7300 : ({ "find", "宝石戒指",        "bao jie",            "", "1" }),
    7400 : ({ "find", "钻石戒指",        "zuan jie",           "", "1" }),
    7500 : ({ "find", "金戒指",          "jin jie",            "", "1" }),
    8000 : ({ "find", "瞌睡虫" ,         "keshui chong",       "", "1" }),
    9000 : ({ "find", HIB"蓝色小草"NOR,  "xiao cao",           "", "1" }),
   10000 : ({ "find", "玉佩",            "yu pei",             "", "1" }),

   10100 : ({ "find", "醋坛子",       "tanzi",                 "", "1" }),
   10200 : ({ "find", "油瓶",         "youping",               "", "1" }),
   10300 : ({ "find", "布袋",         "bag",                   "", "1" }),
   10400 : ({ "find", "饭盒",         "fan he",                "", "1" }),
   10500 : ({ "find", "竹扫帚",       "broom",                 "", "1" }), 
   10600 : ({ "find", "雪饮杯",       "snowglass",             "", "1" }), 
   10700 : ({ "find", "戒尺",         "ruler",                 "", "1" }), 
   10800 : ({ "find", "挂毯",         "gua tan",               "", "1" }),
   10900 : ({ "find", "锡壶",         "xi hu",                 "", "1" }),
   11000 : ({ "find", "锡碗",         "xi wan",                "", "1" }),
   11500 : ({ "find", "雕木斜靠椅",   "yi zi",                 "", "1" }),
   12000 : ({ "find", "镂空木桌",     "zhuo zi",               "", "1" }),
   12500 : ({ "find", "浴巾",         "yu jin",                "", "1" }),
   13000 : ({ "find", "水罐",         "shui guan",             "", "1" }),
   13500 : ({ "find", "油葫芦",       "you hulu",              "", "1" }),
   14000 : ({ "find", "青竹筒",       "qingzhu tong",          "", "1" }),
   14500 : ({ "find", "竹篓",         "zhu lou",               "", "1" }),
   15000 : ({ "find", "水酒罐",       "jiu guan",              "", "1" }),
   15500 : ({ "find", "清白老酒壶",   "jiu hu",                "", "1" }),
   16000 : ({ "find", "白瓷花盆",     "hua pen",               "", "1" }),
   16500 : ({ "find", "青石花瓶",     "hua ping",              "", "1" }),
   17000 : ({ "find", "烫花竹篮",     "zhu lan",               "", "1" }),
   17500 : ({ "find", "细条竹篓",     "zhu lou",               "", "1" }),
   18000 : ({ "find", "银药盏",       "yin yaozhan",           "", "1" }),
   18500 : ({ "find", "白布",         "bai bu",                "", "1" }),
   19000 : ({ "find", "花布",         "hua bu",                "", "1" }),

   20000 : ({ "find", HIB "冰露珠项链" NOR, "icedew lace",     "", "1" }),

   21000 : ({ "find", "荷花灯",       "deng long",             "", "1" }),
   22000 : ({ "find", "莲花灯",       "deng long",             "", "1" }),
   23000 : ({ "find", "雪花灯",       "deng long",             "", "1" }),
   24000 : ({ "find", "桔花灯",       "deng long",             "", "1" }),
   25000 : ({ "find", "梅花灯",       "deng long",             "", "1" }), 
   26000 : ({ "find", "青龙灯",       "deng long",             "", "1" }), 
   27000 : ({ "find", "金凤灯",       "deng long",             "", "1" }), 
   28000 : ({ "find", "麒麟灯",       "deng long",             "", "1" }),
   29000 : ({ "find", "翡翠灯",       "deng long",             "", "1" }),
   30000 : ({ "find", "玉兔灯",       "deng long",             "", "1" }),
   31000 : ({ "find", "兰花灯",       "deng long",             "", "1" }),
   32000 : ({ "find", "朝阳灯",       "deng long",             "", "1" }),
   33000 : ({ "find", "走马灯",       "deng long",             "", "1" }),
   34000 : ({ "find", "绣屏灯",       "deng long",             "", "1" }),
   35000 : ({ "find", "画屏灯",       "deng long",             "", "1" }),
   36000 : ({ "find", "梦幻灯",       "deng long",             "", "1" }),
   37000 : ({ "find", "云雾灯",       "deng long",             "", "1" }),
   38000 : ({ "find", "金鱼灯",       "deng long",             "", "1" }),
   39000 : ({ "find", "仙鹤灯",       "deng long",             "", "1" }),

   40000 : ({ "find", "兽皮",         "shou pi",               "", "1" }),

   41000 : ({ "find", "净瓶",         "jingping",              "", "1" }),

   42000 : ({ "find", "镇妖锤",       "mallet",                "", "1" }),
   43000 : ({ "find", HIC"摄魂匣"NOR, "camera",                "", "1" }),

   45000 : ({ "find", "玻璃盘子",     "panzi",                 "", "1" }),
   46000 : ({ "find", "铁钥匙",       "tie yaoshi",            "", "1" }), 
   50000 : ({ "find", YEL "银簪" NOR,    "clasp",              "", "1" }),

   60000 : ({ "find", "红木道冠",     "bonnet",                "", "1" }),
   70000 : ({ "find", "青木道冠",     "bonnet",                "", "1" }),
   80000 : ({ "find", "珍珠",            "pearl",              "", "1" }),
   90000 : ({ "find", HIR "红丹瓶" NOR,  "hongdan ping",       "", "1" }),
  100000 : ({ "find", HIG "绿丹瓶" NOR,  "lvdan ping",         "", "1" }),
  110000 : ({ "find", HIC "碧水丹" NOR,  "bishui dan",         "", "1" }),
  120000 : ({ "find", "金厢白玉圭",      "yu gui",             "", "1" }),
  310000 : ({ "find", "白鹿头",          "bai lutou",          "", "1" }),
  320000 : ({ "find", "灰羊角",          "hui yangjiao",       "", "1" }),
  330000 : ({ "find", YEL"佛宝舍利子"NOR,"tooth",              "", "1" }),
  340000 : ({ "find", "狮子头",          "shizi tou",          "", "1" }),
  350000 : ({ "find", "牛头",            "niu tou",            "", "1" }),

  360000 : ({ "find", "金龙珠",          "jin longzhu",        "", "1" }),
  370000 : ({ "find", "银龙珠",          "yin longzhu",        "", "1" }),
  380000 : ({ "find", "赤龙珠",          "chi longzhu",        "", "1" }),
  390000 : ({ "find", "橙龙珠",          "cheng longzhu",      "", "1" }),
  400000 : ({ "find", "黄龙珠",          "huang longzhu",      "", "1" }),
  410000 : ({ "find", "绿龙珠",          "lu longzhu",         "", "1" }),
  420000 : ({ "find", "青龙珠",          "qing longzhu",       "", "1" }),
  430000 : ({ "find", "蓝龙珠",          "lan longzhu",        "", "1" }),
  440000 : ({ "find", "紫龙珠",          "zi longzhu",         "", "1" }),

  450000 : ({ "find", "天师法冠",        "loyal bonnet",       "", "1" }),

 1000000 : ({ "find", "九彩云龙珠",      "long zhu",           "", "1" }),
 1200000 : ({ "find", "踏云靴",          "cloudy shoes",       "", "1" }),

]);


